name = "Steam 'n' Rails Modpack"
author = "IThundxr"
version = "1.2.19"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c873ec16016ada5234ffc9335ec576895dfb281236f256b8f568eff03184e690"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
datapack-folder = "config/paxi/datapacks"
