name = "Steam 'n' Rails Modpack"
author = "IThundxr"
version = "1.2.23"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5a1e66f7769b190830a504dc4d8442e7ddd4d01276b470f6d8fe16a758651cab"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
datapack-folder = "config/paxi/datapacks"
