name = "Steam 'n' Rails Modpack"
author = "IThundxr"
version = "1.4.1-hotfix2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d36edced8c13f70527017ce453cb7e743a9fb2e1868b367b3906a86f29e1c26e"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
datapack-folder = "config/paxi/datapacks"
