ServerEvents.recipes((event) => {
    event.shapeless(
        Item.of(
            "createdeco:gold_coin",
            8,
            '{display:{Name:\'[{"text":"Crown","italic":false,"color":"light_purple"}]\'}}'
        ), // arg 1: output
        [
            Item.of(
                "createdeco:netherite_coin",
                1,
                '{display:{Name:\'[{"text":"Sun","italic":false,"color":"dark_purple"}]\'}}'
            ).strongNBT(),
        ]
    );
    event.shapeless(
        Item.of(
            "createdeco:brass_coin",
            8,
            '{display:{Name:\'[{"text":"Cog","italic":false,"color":"dark_blue"}]\'}}'
        ), // arg 1: output
        [
            Item.of(
                "createdeco:gold_coin",
                1,
                '{display:{Name:\'[{"text":"Crown","italic":false,"color":"light_purple"}]\'}}'
            ).strongNBT(),
        ]
    );
    event.shapeless(
        Item.of(
            "createdeco:iron_coin",
            4,
            '{display:{Name:\'[{"text":"Sprocket","italic":false,"color":"red"}]\'}}'
        ), // arg 1: output
        [
            Item.of(
                "createdeco:brass_coin",
                1,
                '{display:{Name:\'[{"text":"Cog","italic":false,"color":"dark_blue"}]\'}}'
            ).strongNBT(),
        ]
    );
    event.shapeless(
        Item.of(
            "createdeco:zinc_coin",
            2,
            '{display:{Name:\'[{"text":"Bevel","italic":false,"color":"aqua"}]\'}}'
        ), // arg 1: output
        [
            Item.of(
                "createdeco:iron_coin",
                1,
                '{display:{Name:\'[{"text":"Sprocket","italic":false,"color":"red"}]\'}}'
            ).strongNBT(),
        ]
    );
    event.shapeless(
        Item.of(
            "createdeco:copper_coin",
            8,
            '{display:{Name:\'[{"text":"Spur","italic":false,"color":"gold"}]\'}}'
        ), // arg 1: output
        [
            Item.of(
                "createdeco:zinc_coin",
                1,
                '{display:{Name:\'[{"text":"Bevel","italic":false,"color":"aqua"}]\'}}'
            ).strongNBT(),
        ]
    );

    event.shapeless(
        Item.of(
            "createdeco:zinc_coin",
            1,
            '{display:{Name:\'[{"text":"Bevel","italic":false,"color":"aqua"}]\'}}'
        ), // arg 1: output
        [
            Item.of(
                "createdeco:copper_coin",
                1,
                '{display:{Name:\'[{"text":"Spur","italic":false,"color":"gold"}]\'}}'
            ).strongNBT(),
            Item.of(
                "createdeco:copper_coin",
                1,
                '{display:{Name:\'[{"text":"Spur","italic":false,"color":"gold"}]\'}}'
            ).strongNBT(),
            Item.of(
                "createdeco:copper_coin",
                1,
                '{display:{Name:\'[{"text":"Spur","italic":false,"color":"gold"}]\'}}'
            ).strongNBT(),
            Item.of(
                "createdeco:copper_coin",
                1,
                '{display:{Name:\'[{"text":"Spur","italic":false,"color":"gold"}]\'}}'
            ).strongNBT(),
            Item.of(
                "createdeco:copper_coin",
                1,
                '{display:{Name:\'[{"text":"Spur","italic":false,"color":"gold"}]\'}}'
            ).strongNBT(),
            Item.of(
                "createdeco:copper_coin",
                1,
                '{display:{Name:\'[{"text":"Spur","italic":false,"color":"gold"}]\'}}'
            ).strongNBT(),
            Item.of(
                "createdeco:copper_coin",
                1,
                '{display:{Name:\'[{"text":"Spur","italic":false,"color":"gold"}]\'}}'
            ).strongNBT(),
            Item.of(
                "createdeco:copper_coin",
                1,
                '{display:{Name:\'[{"text":"Spur","italic":false,"color":"gold"}]\'}}'
            ).strongNBT(),
        ]
    );

    event.shapeless(
        Item.of(
            "createdeco:iron_coin",
            1,
            '{display:{Name:\'[{"text":"Sprocket","italic":false,"color":"red"}]\'}}'
        ), // arg 1: output
        [
            Item.of(
                "createdeco:zinc_coin",
                1,
                '{display:{Name:\'[{"text":"Bevel","italic":false,"color":"aqua"}]\'}}'
            ).strongNBT(),
            Item.of(
                "createdeco:zinc_coin",
                1,
                '{display:{Name:\'[{"text":"Bevel","italic":false,"color":"aqua"}]\'}}'
            ).strongNBT(),
        ]
    );
    event.shapeless(
        Item.of(
            "createdeco:brass_coin",
            1,
            '{display:{Name:\'[{"text":"Cog","italic":false,"color":"dark_blue"}]\'}}'
        ), // arg 1: output
        [
            Item.of(
                "createdeco:iron_coin",
                1,
                '{display:{Name:\'[{"text":"Sprocket","italic":false,"color":"red"}]\'}}'
            ).strongNBT(),
            Item.of(
                "createdeco:iron_coin",
                1,
                '{display:{Name:\'[{"text":"Sprocket","italic":false,"color":"red"}]\'}}'
            ).strongNBT(),
            Item.of(
                "createdeco:iron_coin",
                1,
                '{display:{Name:\'[{"text":"Sprocket","italic":false,"color":"red"}]\'}}'
            ).strongNBT(),
            Item.of(
                "createdeco:iron_coin",
                1,
                '{display:{Name:\'[{"text":"Sprocket","italic":false,"color":"red"}]\'}}'
            ).strongNBT(),
        ]
    );
    event.shapeless(
        Item.of(
            "createdeco:gold_coin",
            1,
            '{display:{Name:\'[{"text":"Crown","italic":false,"color":"light_purple"}]\'}}'
        ), // arg 1: output
        [
            Item.of(
                "createdeco:brass_coin",
                1,
                '{display:{Name:\'[{"text":"Cog","italic":false,"color":"dark_blue"}]\'}}'
            ).strongNBT(),
            Item.of(
                "createdeco:brass_coin",
                1,
                '{display:{Name:\'[{"text":"Cog","italic":false,"color":"dark_blue"}]\'}}'
            ).strongNBT(),
            Item.of(
                "createdeco:brass_coin",
                1,
                '{display:{Name:\'[{"text":"Cog","italic":false,"color":"dark_blue"}]\'}}'
            ).strongNBT(),
            Item.of(
                "createdeco:brass_coin",
                1,
                '{display:{Name:\'[{"text":"Cog","italic":false,"color":"dark_blue"}]\'}}'
            ).strongNBT(),
            Item.of(
                "createdeco:brass_coin",
                1,
                '{display:{Name:\'[{"text":"Cog","italic":false,"color":"dark_blue"}]\'}}'
            ).strongNBT(),
            Item.of(
                "createdeco:brass_coin",
                1,
                '{display:{Name:\'[{"text":"Cog","italic":false,"color":"dark_blue"}]\'}}'
            ).strongNBT(),
            Item.of(
                "createdeco:brass_coin",
                1,
                '{display:{Name:\'[{"text":"Cog","italic":false,"color":"dark_blue"}]\'}}'
            ).strongNBT(),
            Item.of(
                "createdeco:brass_coin",
                1,
                '{display:{Name:\'[{"text":"Cog","italic":false,"color":"dark_blue"}]\'}}'
            ).strongNBT(),
        ]
    );
    event.shapeless(
        Item.of(
            "createdeco:netherite_coin",
            1,
            '{display:{Name:\'[{"text":"Sun","italic":false,"color":"dark_purple"}]\'}}'
        ), // arg 1: output
        [
            Item.of(
                "createdeco:gold_coin",
                1,
                '{display:{Name:\'[{"text":"Crown","italic":false,"color":"light_purple"}]\'}}'
            ).strongNBT(),
            Item.of(
                "createdeco:gold_coin",
                1,
                '{display:{Name:\'[{"text":"Crown","italic":false,"color":"light_purple"}]\'}}'
            ).strongNBT(),
            Item.of(
                "createdeco:gold_coin",
                1,
                '{display:{Name:\'[{"text":"Crown","italic":false,"color":"light_purple"}]\'}}'
            ).strongNBT(),
            Item.of(
                "createdeco:gold_coin",
                1,
                '{display:{Name:\'[{"text":"Crown","italic":false,"color":"light_purple"}]\'}}'
            ).strongNBT(),
            Item.of(
                "createdeco:gold_coin",
                1,
                '{display:{Name:\'[{"text":"Crown","italic":false,"color":"light_purple"}]\'}}'
            ).strongNBT(),
            Item.of(
                "createdeco:gold_coin",
                1,
                '{display:{Name:\'[{"text":"Crown","italic":false,"color":"light_purple"}]\'}}'
            ).strongNBT(),
            Item.of(
                "createdeco:gold_coin",
                1,
                '{display:{Name:\'[{"text":"Crown","italic":false,"color":"light_purple"}]\'}}'
            ).strongNBT(),
            Item.of(
                "createdeco:gold_coin",
                1,
                '{display:{Name:\'[{"text":"Crown","italic":false,"color":"light_purple"}]\'}}'
            ).strongNBT(),
        ]
    );
    event.shapeless(
        Item.of(
            "minecraft:written_book",
            '{author:"NeonCityDrifter",pages:[\'{"text":"Table Of Contents\\\\n1 - Spur\\\\n2 - Bevel \\\\n3 - Sprocket\\\\n4 - Cog\\\\n5 - Crown\\\\n6 - Sun\\\\n7 - Ex. Conversions\\\\n8 - Equivalency Chart\\\\n\\\\n\\\\n\\\\n\\\\nVer. 1.0"}\',\'{"text":"Spur: Smallest coin.\\\\nEquivalent to a penny, the spur is meant for the most menial transactions, and for giving change. \\\\nThere are 64 spur in 1 cog."}\',\'{"text":"Bevel: the \\\\"nickel\\\\". \\\\nThe bevel is meant for simple game payment, and other small transactions.\\\\nThere are 8 bevel in 1 cog."}\',\'{"text":"Sprocket: the \\\\"quarter\\\\".\\\\nSprocket are meant for transport fares, food items, and the like. \\\\nThere are 4 sprocket in 1 cog."}\',\'{"text":"Cog: the standard.\\\\nCog are meant to be the \\\\"anchor\\\\" currency, and are also used for medium-sized transactions like purchasing tools and weapons, or bulk transaction of menial goods."}\',\'{"text":"Crown: the larger one.\\\\nMeant for bigger bulk transactions or purchasing more valuable items, like mechanical components or enchanted tools. \\\\nThere are 8 cog in 1 crown."}\',\'{"text":"Sun: the biggest coin.\\\\nThese are meant for extreme bulk transactions, purchasing whole plots of land or prebuilt vehicles, or other similar activities. There are 8 crown in 1 sun.\\\\n"}\',\'{"text":"Ex. Conversions\\\\n\\\\n2 bevel > 1 sprocket\\\\n16 spur > 1 sprocket\\\\n8 sprocket > 2 cog\\\\n1 sun > 64 cog\\\\n4 crown > 32 cog\\\\n64 sprocket > 2 crown\\\\n"}\',\'{"text":"Equivalency Chart\\\\n\\\\n64 spur > 1 cog\\\\n8 bevel > 1 cog\\\\n4 sprocket > 1 cog\\\\n8 cog > 1 crown\\\\n64 cog > 1 sun\\\\n8 crown > 1 sun"}\'],resolved:1b,title:"Cog Currency"}'
        ), // arg 1: output
        [Item.of("minecraft:book", 1)]
    );
});
