ServerEvents.tags('item', event => {
  console.log('Logging Functioning!')
  const logs = event.get('forge:stripped_logs').getObjectIds()
  const blacklist = Ingredient.of(/.*natures_spirit:stripped_joshua_log.*/)
  logs.forEach(log => {
    if (!blacklist.test(log)) event.add('c:stripped_logs', log)
  })
  event.add('c:stripped_logs', 'betterend:mossy_glowshroom_stripped_log')
  event.add('c:stripped_logs', 'betterend:pythadendron_stripped_log')
  event.add('c:stripped_logs', 'betterend:end_lotus_stripped_log')
  event.add('c:stripped_logs', 'betterend:lacugrove_stripped_log')
  event.add('c:stripped_logs', 'betterend:dragon_tree_stripped_log')
  event.add('c:stripped_logs', 'betterend:tenanea_stripped_log')
  event.add('c:stripped_logs', 'betterend:helix_tree_stripped_log')
  event.add('c:stripped_logs', 'betterend:umbrella_tree_stripped_log')
  event.add('c:stripped_logs', 'betterend:jellyshroom_stripped_log')
  event.add('c:stripped_logs', 'betterend:lucernia_stripped_log')
  event.add('c:stripped_logs', 'betterend:mossy_glowshroom_stripped_bark')
  event.add('c:stripped_logs', 'betterend:pythadendron_stripped_bark')
  event.add('c:stripped_logs', 'betterend:end_lotus_stripped_bark')
  event.add('c:stripped_logs', 'betterend:lacugrove_stripped_bark')
  event.add('c:stripped_logs', 'betterend:dragon_tree_stripped_bark')
  event.add('c:stripped_logs', 'betterend:tenanea_stripped_bark')
  event.add('c:stripped_logs', 'betterend:helix_tree_stripped_bark')
  event.add('c:stripped_logs', 'betterend:umbrella_tree_stripped_bark')
  event.add('c:stripped_logs', 'betterend:jellyshroom_stripped_bark')
  event.add('c:stripped_logs', 'betterend:lucernia_stripped_bark')
  event.add('c:stripped_logs', 'natures_spirit:stripped_joshua_bundle')
})